global:
  defaultStorageClass: ""
  security:
    allowInsecureImages: true
  valkey:
    password: "Admin@123"
fullnameOverride: "valkey"
image:
  debug: false
  registry: registry.lingo.local
  repository: bitnami/valkey
  tag: "8.0.2"
  pullPolicy: IfNotPresent
architecture: standalone
auth:
  enabled: true
commonConfiguration: |-
  databases 20
  appendonly yes
  appendfsync always
  save ""
  maxclients 1024
  maxmemory 8GB
  auto-aof-rewrite-percentage 100
  auto-aof-rewrite-min-size 64mb
  maxmemory-policy volatile-lru
  io-threads 10
  io-threads-do-reads yes

primary:
  disableCommands:
    - FLUSHDB
    - FLUSHALL
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  containerPorts:
    valkey: 6379
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/valkey="true"
    type: "soft"
    key: "kubernetes.service/valkey"
    values:
      - "true"
  persistence:
    size: 50Gi
  service:
    type: NodePort
    ports:
      valkey: 6379
    nodePorts:
      valkey: ""
