apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drawdb
  template:
    metadata:
      labels:
        app: drawdb
    spec:
      containers:
      - name: drawdb
        image: registry.lingo.local/service/drawdb:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        ports:
        - name: http
          containerPort: 80
        env:
        - name: TZ
          value: "Asia/Shanghai"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: drawdb
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.service/drawdb
                    operator: In
                    values:
                      - "true"
              weight: 1
---
apiVersion: v1
kind: Service
metadata:
  name: drawdb
  labels:
    app: drawdb
spec:
  selector:
    app: drawdb
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30128
  type: NodePort
