global:
  storageClass: "openebs-hostpath"
fullnameOverride: "mongodb-sharded"
image:
  registry: registry.lingo.local
  repository: service/mongodb-sharded-sharded
  tag: 7.0.12
  pullPolicy: IfNotPresent
  debug: false
auth:
  enabled: true
  rootUser: root
  rootPassword: "Admin@123"
shards: 3
common:
  mongodb-shardedEnableNumactl: false
  useHostnames: true
  mongodb-shardedEnableIPv6: false
  mongodb-shardedDirectoryPerDB: false
  mongodb-shardedSystemLogVerbosity: 0
  mongodb-shardedDisableSystemLog: false
  mongodb-shardedMaxWaitTimeout: 120
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  containerPorts:
    mongodb-sharded: 27017
  serviceAccount:
    create: true
    automountServiceAccountToken: true
service:
  name: ""
  type: NodePort
  ports:
    mongodb-sharded: 27017
  nodePorts:
    mongodb-sharded: ""
configsvr:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
mongos:
  replicas: 1
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
shardsvr:
  dataNode:
    replicas: 3
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/mongodb-sharded="true"
    type: "soft"
    key: "kubernetes.service/mongodb-sharded"
    values:
      - "true"
  persistence:
    size: 100Gi
  arbiter:
    replicaCount: 0
