global:
  storageClass: "openebs-hostpath"
fullnameOverride: "minio"
image:
  registry: registry.lingo.local
  repository: service/minio
  tag: 2024.7.4
  pullPolicy: IfNotPresent
  debug: false
clientImage:
  registry: registry.lingo.local
  repository: service/minio-client
  tag: 2024.7.3
mode: distributed
auth:
  rootUser: admin
  rootPassword: "Admin@123"
disableWebUI: false
statefulset:
  ## replicaCount*drivesPerNode>=4 && replicaCount>=2
  replicaCount: 4
  drivesPerNode: 1
extraEnvVars:
  - name: TZ
    value: Asia/Shanghai
terminationGracePeriodSeconds: "10"
resourcesPreset: "none"
resources: {}
# resources:
#   limits:
#     cpu: "1"
#     memory: "1Gi"
#   requests:
#     cpu: "500m"
#     memory: "512Mi"
# ## Allowed values: `soft` or `hard`
# #podAffinityPreset: "soft"  ## 调度到同一节点
# podAntiAffinityPreset: "hard"  ## 调度到不同节点
# nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local ateng.kafka.controller=node
#   type: "hard"
#   key: "ateng.kafka.controller"
#   values:
#     - node
# affinity: {}
# nodeSelector: {}
# terminationGracePeriodSeconds: "30"
containerPorts:
  api: 9000
  console: 9001
service:
  type: NodePort
  ports:
    api: 9000
    console: 9001
  nodePorts:
    api: ""
    console: ""
persistence:
  size: 100Gi

