apiVersion: v1
kind: Service
metadata:
  name: vm-lingo02
  namespace: lingo-vm
spec:
  selector:
    kubevirt.io/vm: vm-lingo02
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 40102
  type: NodePort
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-lingo02
  name: vm-lingo02
  namespace: lingo-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-lingo02
      annotations:
        "cni.projectcalico.org/ipAddrs": "[\"10.244.250.52\"]"
    spec:
      nodeSelector:
        kubernetes.io/hostname: server03.lingo.local
      domain:
        cpu:
          cores: 8
          model: host-passthrough
        memory:
          guest: 16Gi
        resources:
          overcommitGuestOverhead: true
        devices:
          disks:
          - name: system
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            bridge: {}
      terminationGracePeriodSeconds: 10
      networks:
      - name: default
        pod: {}
      volumes:
      - name: system
        dataVolume:
          name: vm-lingo02-system
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #!/bin/sh
            echo Admin@123 | passwd --stdin root 
  dataVolumeTemplates:
  - metadata:
      name: vm-lingo02-system
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: openebs-hostpath
      source:
        registry:
          url: "docker://swr.cn-north-1.myhuaweicloud.com/kongyu/kubevirt/linux:centos-7.9-2009-x86_64-01"

