apiVersion: v1
kind: ConfigMap
metadata:
  name: doris-be-configmap
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doris
    app.kubernetes.io/part-of: doris-operator
data:
  be.conf: |
    CUR_DATE=`date +%Y%m%d-%H%M%S`
    PPROF_TMPDIR="$DORIS_HOME/log/"
    JAVA_OPTS="-Xms2048m -Xmx8192m -Dfile.encoding=UTF-8 -DlogPath=$LOG_DIR/jni.log -Xloggc:$DORIS_HOME/log/be.gc.log.$CUR_DATE -Djavax.security.auth.useSubjectCredsOnly=false -Dsun.security.krb5.debug=true -Dsun.java.command=DorisBE -XX:-CriticalJNINatives"
    JAVA_HOME=/usr/lib/jvm/java
    JEMALLOC_CONF="percpu_arena:percpu,background_thread:true,metadata_thp:auto,muzzy_decay_ms:5000,dirty_decay_ms:5000,oversize_threshold:0,prof:false,lg_prof_interval:-1"
    JEMALLOC_PROF_PRFIX="jemalloc_heap_profile_"
    # ports for admin, web, heartbeat service
    be_port = 9060
    webserver_port = 8040
    heartbeat_service_port = 9050
    brpc_port = 8060
    arrow_flight_sql_port = -1
    storage_root_path = ${DORIS_HOME}/storage
    jdbc_drivers_dir = ${DORIS_HOME}/jdbc_drivers
    # INFO, WARNING, ERROR, FATAL
    sys_log_level = INFO
  hdfs-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <property>
            <name>dfs.namenode.rpc-address</name>
            <value>bigdata01:8020</value>
        </property>
    </configuration>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: doris-fe-configmap
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doris
    app.kubernetes.io/part-of: doris-operator
data:
  fe.conf: |
    CUR_DATE=`date +%Y%m%d-%H%M%S`
    LOG_DIR = ${DORIS_HOME}/log
    JAVA_HOME=/usr/lib/jvm/java
    JAVA_OPTS="-Xms2048m -Xmx8192m -Dfile.encoding=UTF-8 -Djavax.security.auth.useSubjectCredsOnly=false -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:$LOG_DIR/fe.gc.log.$CUR_DATE -Dlog4j2.formatMsgNoLookups=true"
    meta_dir = ${DORIS_HOME}/doris-meta
    jdbc_drivers_dir = ${DORIS_HOME}/jdbc_drivers
    http_port = 8030
    rpc_port = 9020
    query_port = 9030
    edit_log_port = 9010
    arrow_flight_sql_port = -1
    log_roll_size_mb = 1024
    # INFO, WARN, ERROR, FATAL
    sys_log_level = WARN
    # NORMAL, BRIEF, ASYNC
    sys_log_mode = NORMAL
    qe_max_connection = 1024
    qe_query_timeout_second = 300
    qe_slow_log_ms = 5000
    enable_fqdn_mode = true
  hdfs-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <property>
            <name>dfs.namenode.rpc-address</name>
            <value>bigdata01:8020</value>
        </property>
    </configuration>
---
apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  name: doris-cluster
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doris
    app.kubernetes.io/part-of: doris-operator
spec:
  authSecret: doris-auth
  feSpec:
    replicas: 3
    podLabels:
      app: doris
      doris: fe
    image: registry.lingo.local/service/doris.fe-ubuntu:2.1.7
    service:
      type: NodePort
    configMapInfo:
      configMapName: doris-fe-configmap
      resolveKey: fe.conf
    limits:
      cpu: 8
      memory: 8Gi
    requests:
      cpu: 100m
      memory: 256Mi
    envVars:
    - name: TZ
      value: Asia/Shanghai
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: kubernetes.service/doris
              operator: In
              values:
              - "true"
          weight: 1
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app: doris
                app.kubernetes.io/component: fe
            topologyKey: kubernetes.io/hostname
          weight: 1
    persistentVolumes:
    - mountPath: /opt/apache-doris/fe/doris-meta
      name: fe-meta
      persistentVolumeClaimSpec:
        #storageClassName: openebs-hostpath
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
    systemInitialization:
      initImage: registry.lingo.local/service/selectdb-alpine:latest
  beSpec:
    replicas: 3
    podLabels:
      app: doris
      doris: be
    image: registry.lingo.local/service/doris.be-ubuntu:2.1.7
    service:
      type: ClusterIP
    configMapInfo:
      configMapName: doris-be-configmap
      resolveKey: be.conf
    limits:
      cpu: 8
      memory: 8Gi
    requests:
      cpu: 100m
      memory: 256Mi
    envVars:
    - name: TZ
      value: Asia/Shanghai
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: kubernetes.service/doris
              operator: In
              values:
              - "true"
          weight: 1
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app: doris
                app.kubernetes.io/component: be
            topologyKey: kubernetes.io/hostname
          weight: 1
    persistentVolumes:
    - mountPath: /opt/apache-doris/be/storage
      name: be-storage
      persistentVolumeClaimSpec:
        #storageClassName: openebs-hostpath
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
    systemInitialization:
      initImage: registry.lingo.local/service/selectdb-alpine:latest
