global:
  defaultStorageClass: ""
fullnameOverride: "etcd"
image:
  registry: registry.lingo.local
  repository: bitnami/etcd
  tag: "3.5.17"
  debug: false
auth:
  rbac:
    create: false
  token:
    enabled: false
  client:
    secureTransport: false
    useAutoTLS: false
    enableAuthentication: false
autoCompactionMode: "periodic"
autoCompactionRetention: "10h"
logLevel: "warn"
replicaCount: 3
extraEnvVars:
  - name: ETCD_QUOTA_BACKEND_BYTES
    value: "8589934592"
  - name: ETCD_MAX_REQUEST_BYTES
    value: "10485760"
  - name: ETCD_SNAPSHOT_COUNT
    value: "2000"
  - name: ETCD_MAX_TXN_OPS
    value: "1280"
  - name: TZ
    value: Asia/Shanghai
resourcesPreset: "none"
resources: {}
affinity: {}
nodeSelector: {}
# resources:
#   limits:
#     cpu: "1"
#     memory: "1Gi"
#   requests:
#     cpu: "500m"
#     memory: "512Mi"
# ## Allowed values: `soft` or `hard`
# #podAffinityPreset: "soft"  ## 调度到同一节点
podAntiAffinityPreset: "soft"  ## 调度到不同节点
nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/etcd="true"
  type: "soft"
  key: "kubernetes.service/etcd"
  values:
    - "true"
service:
  type: NodePort
  enabled: true
  ports:
    client: 2379
    peer: 2380
  nodePorts:
    client: ""
    peer: ""
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 20Gi
startFromSnapshot:
  enabled: false
  existingClaim: ""
  snapshotFilename: ""
disasterRecovery:
  enabled: false
  cronjob:
    schedule: "0 */8 * * *"
  pvc:
    size: 200Gi
    storageClassName: nfs-client
defrag:
  enabled: false
  cronjob:
    schedule: "0 0 * * *"
