global:
  storageClass: "openebs-hostpath"
fullnameOverride: "spark"
image:
  registry: registry.lingo.local
  repository: service/bitnami-spark
  tag: 3.5.1
  pullPolicy: IfNotPresent
  debug: false
hostNetwork: false
master:
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
worker:
  replicaCount: 2
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  resourcesPreset: "none"
  resources: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  # nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local ateng.kafka.controller=node
  #   type: "hard"
  #   key: "ateng.kafka.controller"
  #   values:
  #     - node
  # affinity: {}
  # nodeSelector: {}
  # terminationGracePeriodSeconds: "30"
service:
  type: NodePort
  ports:
    http: 80
    https: 443
    cluster: 7077
  nodePorts:
    http: ""
    https: ""
    cluster: ""
