global:
  defaultStorageClass: ""
fullnameOverride: "gitea"
image:
  registry: registry.lingo.local
  repository: bitnami/gitea
  tag: "1.22.3"
  pullPolicy: IfNotPresent
  debug: false
adminUsername: root
adminPassword: "Admin@123"
adminEmail: 2385569970@qq.com
appName: gitea
runMode: prod
exposeSSH: true
extraEnvVars:
  - name: TZ
    value: "Asia/Shanghai"
  - name: GITEA_DOMAIN
    value: "192.168.1.10"
smtpHost: ""
smtpPort: ""
smtpUser: ""
smtpPassword: ""
containerPorts:
  http: 3000
  ssh: 2222
persistence:
  enabled: true
  size: 100Gi
service:
  type: NodePort
  ports:
    http: 80
    ssh: 32222
  nodePorts:
    http: "33000"
    ssh: "32222"
resourcesPreset: "none"
resources: {}
affinity: {}
nodeSelector: {}
# resources:
#   limits:
#     cpu: "1"
#     memory: "1Gi"
#   requests:
#     cpu: "500m"
#     memory: "512Mi"
# ## Allowed values: `soft` or `hard`
# #podAffinityPreset: "soft"  ## 调度到同一节点
podAntiAffinityPreset: "soft"  ## 调度到不同节点
nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/gitea="true"
  type: "soft"
  key: "kubernetes.service/gitea"
  values:
    - "true"

postgresql:
  enabled: false
externalDatabase:
  host: "postgresql-0.postgresql-hl.kongyu"
  port: 5432
  user: gitea
  database: ateng_gitea
  password: "Admin@123"
