fullnameOverride: "spark-operator"
image:
  registry: registry.lingo.local
  repository: service/spark-operator
  tag: "2.1.0"
  pullPolicy: IfNotPresent
controller:
  replicas: 1
  workers: 10
  # -- Configure the verbosity of logging, can be one of `debug`, `info`, `error`.
  logLevel: info
  # -- Grace period after a successful spark-submit when driver pod not found errors will be retried. Useful if the driver pod can take some time to be created.
  driverPodCreationGracePeriod: 30s
  # -- Specifies the maximum number of Executor pods that can be tracked by the controller per SparkApplication.
  maxTrackedExecutorPerApp: 1000
  uiService:
    # -- Specifies whether to create service for Spark web UI.
    enable: true
  env:
    - name: TZ
      value: Asia/Shanghai
webhook:
  enable: true
  replicas: 1
  # -- Configure the verbosity of logging, can be one of `debug`, `info`, `error`.
  logLevel: info
  env:
    - name: TZ
      value: Asia/Shanghai
spark:
  jobNamespaces:
    - default
    - ateng-spark
prometheus:
  metrics:
    enable: true
    port: 8080
    portName: metrics
    endpoint: /metrics
    prefix: ""
  podMonitor:
    create: false
    labels: {}
    jobLabel: spark-operator-podmonitor
    podMetricsEndpoint:
      scheme: http
      interval: 5s

