apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
data:
  application.yml: |
    server:
      port: 7091
    spring:
      application:
        name: seata-server
    logging:
      config: classpath:logback-spring.xml
      file:
        path: ${log.home:${user.home}/logs/seata}
    console:
      user:
        username: admin
        password: Admin@123
    seata:
      config:
        type: nacos
        nacos:
          server-addr: 192.168.1.10:30648
          namespace: 3ac1b8fa-0fb1-4aa2-9858-374af73825f3
          group: SEATA_GROUP
          username: nacos
          password: Admin@123
          data-id: seataServer.properties
      registry:
        type: nacos
        nacos:
          cluster: atengSeata
          server-addr: ${seata.config.nacos.server-addr}
          namespace: ${seata.config.nacos.namespace}
          group: ${seata.config.nacos.group}
          username: ${seata.config.nacos.username}
          password: ${seata.config.nacos.password}
      server:
        service-port: 8091 #If not configured, the default is '${server.port} + 1000'
        max-commit-retry-timeout: -1
        max-rollback-retry-timeout: -1
        rollback-retry-timeout-unlock-enable: false
        enable-check-auth: true
        enable-parallel-request-handle: true
        enable-parallel-handle-branch: false
        retry-dead-threshold: 130000
        xaer-nota-retry-timeout: 60000
        enableParallelRequestHandle: true
        applicationDataLimitCheck: true
        applicationDataLimit: 64000
        recovery:
          committing-retry-period: 1000
          async-committing-retry-period: 1000
          rollbacking-retry-period: 1000
          timeout-retry-period: 1000
        undo:
          log-save-days: 7
          log-delete-period: 86400000
        session:
          branch-async-queue-size: 5000 #branch async remove queue size
          enable-branch-async-remove: false #enable to asynchronous remove branchSession
      store:
        mode: db
        session:
          mode: db
        lock:
          mode: db
        db:
          datasource: druid
          db-type: mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.10:35725/ateng_seata?rewriteBatchedStatements=true
          user: root
          password: Admin@123
          min-conn: 10
          max-conn: 100
          global-table: global_table
          branch-table: branch_table
          lock-table: lock_table
          distributed-lock-table: distributed_lock
          vgroup-table: vgroup_table
          query-limit: 1000
          max-wait: 5000
      metrics:
        enabled: false
        registry-type: compact
        exporter-list: prometheus
        exporter-prometheus-port: 9898
      transport:
        rpc-tc-request-timeout: 15000
        enable-tc-server-batch-send-response: false
        shutdown:
          wait: 3
        thread-factory:
          boss-thread-prefix: NettyBoss
          worker-thread-prefix: NettyServerNIOWorker
          boss-thread-size: 1
      security:
        secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
        tokenValidityInMilliseconds: 1800000
        csrf-ignore-urls: /metadata/v1/**
        ignore:
          urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login,/version.json,/health,/error,/vgroup/v1/**
    
---
apiVersion: v1
kind: Service
metadata:
  name: seata-server
  labels:
    app: seata-server
spec:
  type: NodePort
  ports:
    - port: 38091
      protocol: TCP
      name: netty
      nodePort: 38091
    - port: 7091
      protocol: TCP
      name: http
      nodePort: 37091
  selector:
    app: seata-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-server
  labels:
    app: seata-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seata-server
  template:
    metadata:
      labels:
        app: seata-server
    spec:
      containers:
        - name: seata-server
          image: registry.lingo.local/service/seata-server:2.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: netty
              containerPort: 38091
              protocol: TCP
            - name: http
              containerPort: 7091
              protocol: TCP
          volumeMounts:
            - name: seata-config
              mountPath: /seata-server/conf/application.yml
              subPath: 'application.yml'
          livenessProbe:
            httpGet:
              path: /version.json
              port: 7091
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /version.json
              port: 7091
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
          env:
          - name: TZ
            value: "Asia/Shanghai"
          - name: JVM_XMX
            value: "2g"
          - name: JVM_XMS
            value: "512m"
          - name: SEATA_IP
            value: 192.168.1.10
          - name: SEATA_PORT
            value: "38091"
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: seata-config
          configMap:
            name: seata-server-config
            items:
              - key: application.yml
                path: application.yml
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: seata-server
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.service/seata-server
                    operator: In
                    values:
                      - "true"
              weight: 1
