global:
  defaultStorageClass: ""
fullnameOverride: "kafka"
image:
  registry: registry.lingo.local
  repository: bitnami/kafka
  tag: "3.8.1"
  pullPolicy: IfNotPresent
  debug: false
heapOpts: -Xmx4096m -Xms1024m
listeners:
  client:
    containerPort: 9092
    protocol: PLAINTEXT
    name: CLIENT
    sslClientAuth: "none"
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: PLAINTEXT
    sslClientAuth: "none"
  interbroker:
    containerPort: 9094
    protocol: PLAINTEXT
    name: INTERNAL
    sslClientAuth: "none"
  external:
    containerPort: 9095
    protocol: PLAINTEXT
    name: EXTERNAL
    sslClientAuth: "none"
extraEnvVars:
  - name: TZ
    value: Asia/Shanghai
controller:
  replicaCount: 1
  controllerOnly: false
  minId: 0
  zookeeperMigrationMode: false
  heapOpts: -Xmx4096m -Xms1024m
  automountServiceAccountToken: true
  extraConfig: |
    num.io.threads=3
    num.network.threads=3
    num.partitions=1
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=1
    default.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    auto.create.topics.enable=true
    delete.topic.enable=true
    log.retention.hours=8
    log.retention.bytes=1073741824
    log.retention.check.interval.ms=300000
    log.segment.bytes=1073741824
    max.partition.fetch.bytes=104857600
    max.request.size=104857600
    message.max.bytes=104857600
    fetch.max.bytes=104857600
    replica.fetch.max.bytes=104857600
  persistence:
    enabled: true
    size: 100Gi
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/kafka="true"
    type: "soft"
    key: "kubernetes.service/kafka"
    values:
      - "true"
broker:
  replicaCount: 0
service:
  type: NodePort
  ports:
    client: 9092
    controller: 9093
    interbroker: 9094
    external: 9095
  nodePorts:
    client: ""
    external: ""
rbac:
  create: true
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
    image:
      registry: registry.lingo.local
      repository: bitnami/kubectl
      tag: "1.31.2"
    resourcesPreset: "none"
    resources: {}
  controller:
    forceExpose: false
    service:
      type: NodePort
      ports:
        external: 9095
  broker:
    service:
      type: NodePort
      ports:
        external: 9095
