global:
  defaultStorageClass: ""
  security:
    allowInsecureImages: true
fullnameOverride: "grafana"
image:
  registry: registry.lingo.local
  repository: bitnami/grafana
  tag: "11.5.3"
  pullPolicy: IfNotPresent
admin:
  user: "admin"
  password: "Admin@123"
smtp:
  enabled: false
  user: user
  password: password
  host: ""
  fromAddress: ""
  fromName: ""
  skipVerify: "false"
## plugins: grafana-kubernetes-app,grafana-example-app
plugins: ""
grafana:
  replicaCount: 1
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/grafana="true"
    type: "soft"
    key: "kubernetes.service/grafana"
    values:
      - "true"
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
persistence:
  enabled: true
  size: 10Gi
service:
  type: NodePort
  ports:
    grafana: 3000
  nodePorts:
    grafana: ""
