global:
  storageClass: "openebs-hostpath"
  kibanaEnabled: false
fullnameOverride: "elasticsearch"
#plugins: "http://miniserve.lingo.local/elasticsearch-plugins/v8.11.3/analysis-icu-8.11.3.zip http://miniserve.lingo.local/elasticsearch-plugins/v8.11.3/analysis-phonetic-8.11.3.zip http://miniserve.lingo.local/elasticsearch-plugins/v8.11.3/analysis-smartcn-8.11.3.zip http://miniserve.lingo.local/elasticsearch-plugins/v8.11.3/analysis-ik-8.11.3.zip"
#plugins: "https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-phonetic/analysis-phonetic-8.11.3.zip https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-icu/analysis-icu-8.11.3.zip https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-smartcn/analysis-smartcn-8.11.3.zip"
plugins: ""
snapshotRepoPath: "/bitnami/elasticsearch/data/snap"
extraConfig:
  xpack:
    security:
      enabled: false
  http:
    cors:
      enabled: true
      allow-origin: "*"
extraEnvVars:
  - name: TZ
    value: Asia/Shanghai
image:
  registry: registry.lingo.local
  repository: service/elasticsearch
  tag: 8.11.3
  pullPolicy: IfNotPresent
  debug: false
security:
  enabled: false
  elasticPassword: ""
  fipsMode: false
  tls:
    restEncryption: true
    autoGenerated: false
    verificationMode: "full"
    usePemCerts: false
service:
  type: NodePort
  ports:
    restAPI: 9200
    transport: 9300
  nodePorts:
    restAPI: ""
    transport: ""
master:
  masterOnly: true
  replicaCount: 2
  extraRoles: []
  heapSize: 1024m
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits: {}
    requests: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  # podAntiAffinityPreset: "hard"  ## 调度到不同节点
  # nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local ateng.kafka.controller=node
  #   type: "hard"
  #   key: "ateng.kafka.controller"
  #   values:
  #     - node
  # affinity: {}
  # nodeSelector: {}
  # terminationGracePeriodSeconds: "30"
data:
  replicaCount: 2
  extraRoles: []
  heapSize: 2048m
  persistence:
    enabled: true
    size: 100Gi
  resources:
    limits: {}
    requests: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  # podAntiAffinityPreset: "hard"  ## 调度到不同节点
  # nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local ateng.kafka.controller=node
  #   type: "hard"
  #   key: "ateng.kafka.controller"
  #   values:
  #     - node
  # affinity: {}
  # nodeSelector: {}
  # terminationGracePeriodSeconds: "30"
coordinating:
  replicaCount: 2
  extraRoles: []
  heapSize: 1024m
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits: {}
    requests: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  # podAntiAffinityPreset: "hard"  ## 调度到不同节点
  # nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local ateng.kafka.controller=node
  #   type: "hard"
  #   key: "ateng.kafka.controller"
  #   values:
  #     - node
  # affinity: {}
  # nodeSelector: {}
  # terminationGracePeriodSeconds: "30"
ingest:
  enabled: true
  replicaCount: 2
  extraRoles: []
  containerPorts:
    restAPI: 9200
    transport: 9300
  heapSize: 1024m
  service:
    enabled: false
    type: ClusterIP
    ports:
      restAPI: 9200
      transport: 9300
    nodePorts:
      restAPI: ""
      transport: ""
  resources:
    limits: {}
    requests: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  # podAntiAffinityPreset: "hard"  ## 调度到不同节点
  # nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local ateng.kafka.controller=node
  #   type: "hard"
  #   key: "ateng.kafka.controller"
  #   values:
  #     - node
  # affinity: {}
  # nodeSelector: {}
  # terminationGracePeriodSeconds: "30"
metrics:
  enabled: false
  image:
    registry: registry.lingo.local
    repository: service/elasticsearch-exporter
    tag: 1.6.0
    pullPolicy: IfNotPresent
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-weight: "5"
  service:
    type: ClusterIP
    port: 9114
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9114"
  serviceMonitor:
    enabled: false
    namespace: ""
    jobLabel: ""
    interval: ""
    scrapeTimeout: ""
    relabelings: []
    metricRelabelings: []
    selector: {}
    labels: {}
    honorLabels: false
  prometheusRule:
    enabled: false
    namespace: ""
    additionalLabels: {}
    rules: []
volumePermissions:
  enabled: true
  image:
    registry: registry.lingo.local
    repository: service/os-shell
    tag: 11
    pullPolicy: IfNotPresent
sysctlImage:
  enabled: true
  registry: registry.lingo.local
  repository: service/os-shell
  tag: 11
  pullPolicy: IfNotPresent
