global:
  defaultStorageClass: ""
  security:
    allowInsecureImages: true
fullnameOverride: "zipkin"
image:
  registry: registry.lingo.local
  repository: bitnami/zipkin
  tag: "3.4.4"
  pullPolicy: IfNotPresent
  debug: false
javaOpts: ""
replicaCount: 1
storageType: cassandra3
tls:
  enabled: false
extraEnvVars:
  - name: TZ
    value: "Asia/Shanghai"
resourcesPreset: "none"
resources: {}
affinity: {}
nodeSelector: {}
podAntiAffinityPreset: "soft"  ## 调度到不同节点
nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/zipkin="true"
  type: "soft"
  key: "kubernetes.service/zipkin"
  values:
    - "true"
persistence:
  enabled: true
  size: 100Gi
service:
  type: NodePort
  ports:
    http: 9411
  nodePorts:
    http: ""
defaultInitContainers:
  waitForCassandra:
    enabled: true
    image:
      registry: registry.lingo.local
      repository: bitnami/cassandra
      tag: "5.0.3"
      pullPolicy: IfNotPresent
      debug: false
    resourcesPreset: "none"
    resources: {}
  initCerts:
    enabled: false
    resourcesPreset: "none"
    resources: {}
cassandra:
  enabled: true
  image:
    registry: registry.lingo.local
    repository: bitnami/cassandra
    tag: "5.0.3"
    pullPolicy: IfNotPresent
    debug: false
  cluster:
    datacenter: "datacenter1"
  keyspace: "ateng_zipkin"
  dbUser:
    user: cassandra
    password: "Admin@123"
  service:
    ports:
      cql: 9042
  replicaCount: 1
  resourcesPreset: "none"
  resources: {}
  initDB:
    create_keyspace.cql: |
      CREATE KEYSPACE {{ include "zipkin.cassandra.keyspace" . }} WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
  extraEnvVars:
    - name: CASSANDRA_CFG_YAML_SASI_INDEXES_ENABLED
      value: "true"
    - name: TZ
      value: "Asia/Shanghai"
  persistence:
    enabled: true
    size: 100Gi
    commitLogsize: 10Gi
