global:
  storageClass: "openebs-hostpath"
fullnameOverride: "mongodb"
image:
  registry: registry.lingo.local
  repository: service/mongodb
  tag: 7.0.12
  pullPolicy: IfNotPresent
  debug: false
architecture: standalone
useStatefulSet: true
auth:
  enabled: true
  rootUser: root
  rootPassword: "Admin@123"
  usernames: [kongyu01,kongyu02]
  passwords: [kongyu01,kongyu02]
  databases: [kongyu01,kongyu02]
enableIPv6: false
directoryPerDB: false
systemLogVerbosity: 0
disableSystemLog: true
disableJavascript: false
enableJournal: true
extraEnvVars:
  - name: TZ
    value: Asia/Shanghai
replicaCount: 1
resourcesPreset: "none"
resources: {}
affinity: {}
nodeSelector: {}
# resources:
#   limits:
#     cpu: "1"
#     memory: "1Gi"
#   requests:
#     cpu: "500m"
#     memory: "512Mi"
# ## Allowed values: `soft` or `hard`
# #podAffinityPreset: "soft"  ## 调度到同一节点
podAntiAffinityPreset: "soft"  ## 调度到不同节点
nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/mongodb="true"
  type: "soft"
  key: "kubernetes.service/mongodb"
  values:
    - "true"
containerPorts:
  mongodb: 27017
service:
  type: NodePort
  portName: mongodb
  ports:
    mongodb: 27017
  nodePorts:
    mongodb: ""
  externalTrafficPolicy: Cluster
persistence:
  enabled: true
  size: 100Gi
