
tunnelProtocol: ""  # 隧道协议，用于跨节点通信。设置为空表示不使用隧道，依赖原生路由模式。
routingMode: native  # 路由模式设置为原生模式，直接使用路由表实现节点间的通信，不依赖隧道协议。

ipam:                   # IP 地址管理（IPAM）配置
  mode: kubernetes      # 使用 Kubernetes 的 IPAM 模式，Kubernetes 将负责 IP 地址的分配。

k8s:
  requireIPv4PodCIDR: true   # 是否要求 IPv4 Pod CIDR。设置为 true 表示需要在 Kubernetes 中配置 IPv4 地址池。
  requireIPv6PodCIDR: false  # 是否要求 IPv6 Pod CIDR。设置为 false 表示不需要 IPv6 地址池。

autoDirectNodeRoutes: true  # 自动启用节点直连路由。Cilium 会在节点间自动创建直连路由，实现跨节点的无隧道通信。

ipv4NativeRoutingCIDR: "10.100.0.0/16"  # 指定 IPv4 的原生路由 CIDR，位于此范围内的流量将直接路由，无需隧道。
ipv6NativeRoutingCIDR: "fd00::/104"     # 指定 IPv6 的原生路由 CIDR，位于此范围内的流量将直接路由，无需隧道。

kubeProxyReplacement: true  # 是否替代 kube-proxy。设为 true 则使用 Cilium 的 eBPF 功能完全替代 kube-proxy。

image:
  repository: "registry.lingo.local/kubernetes/cilium"
  tag: "v1.16.3"
  pullPolicy: "IfNotPresent"
  useDigest: false
envoy:
  image:
    repository: "registry.lingo.local/kubernetes/cilium-envoy"
    tag: "v1.29.9-1728346947-0d05e48bfbb8c4737ec40d5781d970a550ed2bbd"
    pullPolicy: "IfNotPresent"
    useDigest: false
operator:
  image:
    repository: "registry.lingo.local/kubernetes/operator"
    tag: "v1.16.3"
    useDigest: false
    pullPolicy: "IfNotPresent"
  replicas: 2
