apiVersion: v2
name: springboot-app
description: A Helm chart for deploying a Spring Boot application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x

