# Source: juicefs-csi-driver/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    helm.sh/chart: juicefs-csi-driver-0.13.1
    app.kubernetes.io/name: juicefs-csi-driver
    app.kubernetes.io/instance: juicefs
    app.kubernetes.io/version: "0.17.1"
    app.kubernetes.io/managed-by: Helm
  name: juicefs
mountOptions:
  - cache-size=2048
  - cache-dir=/var/foo
parameters:
  csi.storage.k8s.io/node-publish-secret-name: juicefs-secret
  csi.storage.k8s.io/node-publish-secret-namespace: "juicefs"
  csi.storage.k8s.io/provisioner-secret-name: juicefs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: "juicefs"
  juicefs/mount-cpu-limit: "1Gi"
  juicefs/mount-memory-limit: "1"
  juicefs/mount-cpu-request: "100m"
  juicefs/mount-memory-request: "100Mi"
  juicefs/mount-image: registry.lingo.local/kubernetes/juicefs-mount:v1.0.0-4.8.0
provisioner: csi.juicefs.com
reclaimPolicy: Delete
volumeBindingMode: Immediate

