nameOverride: ""
fullnameOverride: "skywalking"
initContainer:
  image: registry.lingo.local/service/busybox
  tag: '1.30'

oap:
  name: oap
  image:
    repository: registry.lingo.local/service/skywalking-oap-server
    tag: 9.7.0  # Must be set explicitly
    pullPolicy: IfNotPresent
  storageType: elasticsearch
  ports:
    # add more ports here if you need, for example
    # zabbix: 10051
    grpc: 11800
    rest: 12800
  replicas: 2
  service:
    type: ClusterIP
  javaOpts: -Xmx1g -Xms1g
  env:
    TZ: "Asia/Shanghai"

ui:
  name: ui
  replicas: 1
  image:
    repository: registry.lingo.local/service/skywalking-ui
    tag: 9.7.0  # Must be set explicitly
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    externalPort: 80
    internalPort: 8080
  env:
    TZ: "Asia/Shanghai"
    
elasticsearch:
  enabled: false
  config:               # For users of an existing elasticsearch cluster,takes effect when `elasticsearch.enabled` is false
    port:
      http: 9200
    host: elasticsearch.lingo-service-dev # es service on kubernetes or host
    user: "elastic"         # [optional]
    password: "Admin@123"     # [optional]

satellite:
  name: satellite
  replicas: 1
  enabled: false
  image:
    repository: registry.lingo.local/service/skywalking-satellite
    tag: v1.2.0 # Must be set explicitly
    pullPolicy: IfNotPresent
  ports:
    grpc: 11800
    prometheus: 1234
  service:
    type: ClusterIP
