apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: redis-standalone
  namespace: kongyu
spec:
  terminationPolicy: Delete
  affinity:
    podAntiAffinity: Preferred
    topologyKeys:
      - kubernetes.io/hostname
    tenancy: SharedNode
  clusterDefinitionRef: redis
  topology: standalone
  componentSpecs:
  - name: redis
    replicas: 1
    componentDef: redis-7
    serviceVersion: 7.2.4
    enabledLogs:
      - running
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 1Gi       
    env:
      - name: TZ
        value: Asia/Shanghai
    services:
      - name: redis
        serviceType: NodePort
    volumeClaimTemplates:
      - name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
