apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-test
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
  namespace: default
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/kongyu/busybox:vlatest
    imagePullPolicy: IfNotPresent
    command:
       - sh
       - -c
       - 'while true; do echo $(date) | tee -a /data/date.txt; sleep 1; done'
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: busybox-test
---
