global:
  defaultStorageClass: ""
fullnameOverride: "minio"
image:
  registry: registry.lingo.local
  repository: bitnami/minio
  tag: "2024.11.7"
  pullPolicy: IfNotPresent
  debug: false
clientImage:
  registry: registry.lingo.local
  repository: bitnami/minio-client
  tag: "2024.11.17"
mode: standalone
auth:
  rootUser: admin
  rootPassword: "Admin@123"
defaultBuckets: "bucket01:public,bucket02"
disableWebUI: false
extraEnvVars:
  - name: TZ
    value: Asia/Shanghai
terminationGracePeriodSeconds: "10"
resourcesPreset: "none"
resources: {}
affinity: {}
nodeSelector: {}
podAntiAffinityPreset: "soft"  ## 调度到不同节点
nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/minio="true"
  type: "soft"
  key: "kubernetes.service/minio"
  values:
    - "true"
containerPorts:
  api: 9000
  console: 9001
service:
  type: NodePort
  ports:
    api: 9000
    console: 9001
  nodePorts:
    api: ""
    console: ""
persistence:
  size: 100Gi
