apiVersion: v1
kind: ConfigMap
metadata:
  name: doris-be-configmap
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doris
    app.kubernetes.io/part-of: doris-operator
data:
  be.conf: |
    CUR_DATE=`date +%Y%m%d-%H%M%S`
    PPROF_TMPDIR="$DORIS_HOME/log/"
    JAVA_OPTS="-Xss1024m -Xmx10240m -DlogPath=$DORIS_HOME/log/jni.log -Xloggc:$DORIS_HOME/log/be.gc.log.$CUR_DATE -Djavax.security.auth.useSubjectCredsOnly=false -Dsun.java.command=DorisBE -XX:-CriticalJNINatives -DJDBC_MIN_POOL=1 -DJDBC_MAX_POOL=100 -DJDBC_MAX_IDLE_TIME=300000 -DJDBC_MAX_WAIT_TIME=5000"
    JEMALLOC_CONF="percpu_arena:percpu,background_thread:true,metadata_thp:auto,muzzy_decay_ms:15000,dirty_decay_ms:15000,oversize_threshold:0,lg_tcache_max:20,prof:false,lg_prof_interval:32,lg_prof_sample:19,prof_gdump:false,prof_accum:false,prof_leak:false,prof_final:false"
    JEMALLOC_PROF_PRFIX=""
    # INFO, WARNING, ERROR, FATAL
    sys_log_level = INFO
    # ports for admin, web, heartbeat service
    be_port = 9060
    webserver_port = 8040
    heartbeat_service_port = 9050
    brpc_port = 8060
  hdfs-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <property>
            <name>dfs.namenode.rpc-address</name>
            <value>bigdata01:8020</value>
        </property>
    </configuration>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: doris-fe-configmap
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doris
    app.kubernetes.io/part-of: doris-operator
data:
  fe.conf: |
    CUR_DATE=`date +%Y%m%d-%H%M%S`
    LOG_DIR = ${DORIS_HOME}/log
    JAVA_OPTS="-Xss1024m -Xmx8192m -Djavax.security.auth.useSubjectCredsOnly=false -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:$DORIS_HOME/log/fe.gc.log.$CUR_DATE"
    # INFO, WARN, ERROR, FATAL
    sys_log_level = WARN
    # NORMAL, BRIEF, ASYNC
    sys_log_mode = BRIEF
    qe_max_connection = 10240
    qe_query_timeout_second = 300
    qe_slow_log_ms = 5000
    http_port = 8030
    rpc_port = 9020
    query_port = 9030
    edit_log_port = 9010
    enable_fqdn_mode = true
  hdfs-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <property>
            <name>dfs.namenode.rpc-address</name>
            <value>bigdata01:8020</value>
        </property>
    </configuration>
---
apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  name: doris-cluster
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doris
    app.kubernetes.io/part-of: doris-operator
spec:
  authSecret: doris-auth
  feSpec:
    replicas: 3
    podLabels:
      app: doris
      doris: fe
    image: registry.lingo.local/service/doris.fe-ubuntu:2.1.7
    service:
      type: NodePort
    configMapInfo:
      configMapName: doris-fe-configmap
      resolveKey: fe.conf
    limits:
      cpu: 8
      memory: 8Gi
    requests:
      cpu: 100m
      memory: 256Mi
    envVars:
    - name: TZ
      value: Asia/Shanghai
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: kubernetes.service/doris
              operator: In
              values:
              - "true"
          weight: 1
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app: doris
                app.kubernetes.io/component: fe
            topologyKey: kubernetes.io/hostname
          weight: 1
    persistentVolumes:
    - mountPath: /opt/apache-doris/fe/doris-meta
      name: fe-meta
      persistentVolumeClaimSpec:
        #storageClassName: openebs-hostpath
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
    systemInitialization:
      initImage: registry.lingo.local/service/selectdb-alpine:latest
  beSpec:
    replicas: 3
    podLabels:
      app: doris
      doris: be
    image: registry.lingo.local/service/doris.be-ubuntu:2.1.7
    service:
      type: ClusterIP
    configMapInfo:
      configMapName: doris-be-configmap
      resolveKey: be.conf
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 100m
      memory: 256Mi
    envVars:
    - name: TZ
      value: Asia/Shanghai
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: kubernetes.service/doris
              operator: In
              values:
              - "true"
          weight: 1
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app: doris
                app.kubernetes.io/component: be
            topologyKey: kubernetes.io/hostname
          weight: 1
    persistentVolumes:
    - mountPath: /opt/apache-doris/be/storage
      name: be-storage
      persistentVolumeClaimSpec:
        #storageClassName: openebs-hostpath
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
    systemInitialization:
      initImage: registry.lingo.local/service/selectdb-alpine:latest
