apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-configmap
  labels:
    app.kubernetes.io/component: ms
data:
  doris_cloud.conf: |
    # // meta_service
    brpc_listen_port = 5000
    brpc_num_threads = -1
    brpc_idle_timeout_sec = 30
    http_token = greedisgood9999

    # // doris txn config
    label_keep_max_second = 259200
    expired_txn_scan_key_nums = 1000

    # // logging
    log_dir = ./log/
    # info warn error
    log_level = info
    log_size_mb = 1024
    log_filenum_quota = 10
    log_immediate_flush = false
    # log_verbose_modules = *

    # //max stage num
    max_num_stages = 40

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-configmap
  labels:
    app.kubernetes.io/component: fe
data:
  fe.conf: |
    CUR_DATE=`date +%Y%m%d-%H%M%S`
    LOG_DIR = ${DORIS_HOME}/log
    JAVA_OPTS_FOR_JDK_17="-Xmx8192m -Xms8192m -Dfile.encoding=UTF-8 -Djavax.security.auth.useSubjectCredsOnly=false -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=$LOG_DIR -Xlog:gc*:$LOG_DIR/fe.gc.log.$CUR_DATE:time,uptime:filecount=10,filesize=50M --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens java.base/jdk.internal.ref=ALL-UNNAMED"
    JAVA_HOME=/usr/lib/jvm/java
    meta_dir = ${DORIS_HOME}/doris-meta
    jdbc_drivers_dir = ${DORIS_HOME}/jdbc_drivers
    http_port = 8030
    rpc_port = 9020
    query_port = 9030
    edit_log_port = 9010
    arrow_flight_sql_port = -1
    log_roll_size_mb = 1024
    # INFO, WARN, ERROR, FATAL
    sys_log_level = INFO
    # NORMAL, BRIEF, ASYNC
    sys_log_mode = ASYNC
    deploy_mode=cloud
    enable_fqdn_mode=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: be-configmap
  labels:
    app.kubernetes.io/component: be
data:
  be.conf: |
    CUR_DATE=`date +%Y%m%d-%H%M%S`
    LOG_DIR="${DORIS_HOME}/log/"
    JAVA_OPTS_FOR_JDK_17="-Xms2048m -Xmx8192m -Dfile.encoding=UTF-8 -DlogPath=$LOG_DIR/jni.log -Xlog:gc*:$LOG_DIR/be.gc.log.$CUR_DATE:time,uptime:filecount=10,filesize=50M -Djavax.security.auth.useSubjectCredsOnly=false -Dsun.security.krb5.debug=true -Dsun.java.command=DorisBE -XX:-CriticalJNINatives -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED"
    JAVA_HOME=/usr/lib/jvm/java
    JEMALLOC_CONF="percpu_arena:percpu,background_thread:true,metadata_thp:auto,muzzy_decay_ms:15000,dirty_decay_ms:15000,oversize_threshold:0,prof:false,lg_prof_interval:32,lg_prof_sample:19,prof_gdump:false,prof_accum:false,prof_leak:false,prof_final:false"
    JEMALLOC_PROF_PRFIX=""
    be_port = 9060
    webserver_port = 8040
    heartbeat_service_port = 9050
    brpc_port = 8060
    arrow_flight_sql_port = -1
    # INFO, WARNING, ERROR, FATAL
    sys_log_level = INFO
    deploy_mode = cloud
    enable_file_cache = true
    # 程序会自动挂载到设置的这个目上
    file_cache_path = [{"path":"/data/service/doris/file_cache01","total_size":214748364800,"query_limit":214748364800}]
---
apiVersion: disaggregated.cluster.doris.com/v1
kind: DorisDisaggregatedCluster
metadata:
  name: doris-cluster
spec:
  authSecret: doris-auth
  metaService:
    replicas: 3
    image: registry.lingo.local/service/doris.ms-ubuntu:3.0.3
    fdb:
      configMapNamespaceName:
        name: ateng-cluster-config
        namespace: foundationdb
    configMaps:
    - name: ms-configmap
      mountPath: /etc/doris
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 256Mi
    envVars:
    - name: TZ
      value: Asia/Shanghai
    systemInitialization:
      initImage: registry.lingo.local/service/selectdb-alpine:latest
  feSpec:
    replicas: 3
    image: registry.lingo.local/service/doris.fe-ubuntu:3.0.3
    service: 
      type: NodePort
    configMaps:
    - name: fe-configmap
      mountPath: /etc/doris
    limits:
      cpu: 8
      memory: 8Gi
    requests:
      cpu: 100m
      memory: 256Mi
    envVars:
    - name: TZ
      value: Asia/Shanghai
    persistentVolume:
      logNotStore: true
      persistentVolumeClaimSpec:
        #storageClassName: openebs-hostpath
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
    systemInitialization:
      initImage: registry.lingo.local/service/selectdb-alpine:latest
  computeGroups:
    - uniqueId: cg1
      replicas: 3
      image: registry.lingo.local/service/doris.be-ubuntu:3.0.3
      configMaps:
      - name: be-configmap
        mountPath: /etc/doris
      limits:
        cpu: 8
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 256Mi
      envVars:
      - name: TZ
        value: Asia/Shanghai
      # 这里只是临时解决计算组没有挂载authSecret的问题
      - name: USER
        value: doris
      - name: PASSWD
        value: Doris@2024
      persistentVolume:
        logNotStore: true
        persistentVolumeClaimSpec:
          #storageClassName: openebs-hostpath
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 500Gi
      systemInitialization:
        initImage: registry.lingo.local/service/selectdb-alpine:latest
