global:
  defaultStorageClass: ""
fullnameOverride: "postgresql"
image:
  registry: registry.lingo.local
  repository: bitnami/postgresql
  tag: "16.6.0"
  pullPolicy: IfNotPresent
  debug: false
auth:
  enablePostgresUser: true
  postgresPassword: "Admin@123"
  username: "kongyu"
  password: "kongyu"
  database: "kongyu"
architecture: replication
replication:
  synchronousCommit: "on"
  # 不超过 readReplicas
  numSynchronousReplicas: 2
  applicationName: my_application
containerPorts:
  postgresql: 5432
audit:
  logHostname: false
  logConnections: false
  logDisconnections: false
  pgAuditLog: ""
  pgAuditLogCatalog: "off"
  clientMinMessages: error
  logLinePrefix: ""
  logTimezone: "Asia/Shanghai"
primary:
  name: primary
  extendedConfiguration: |-
    max_connections = 1024
    shared_buffers = 4GB
    work_mem = 64MB
    max_parallel_workers_per_gather = 4
    max_parallel_maintenance_workers = 2
    max_parallel_workers = 8
    wal_level = logical
    log_timezone = Asia/Shanghai
    timezone = Asia/Shanghai
  service:
    type: NodePort
    ports:
      postgresql: 5432
  persistence:
    size: 100Gi
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/postgresql="true"
    type: "soft"
    key: "kubernetes.service/postgresql"
    values:
      - "true"
readReplicas:
  name: read
  replicaCount: 2
  extendedConfiguration: |-
    max_connections = 1024
    shared_buffers = 4GB
    work_mem = 64MB
    max_parallel_workers_per_gather = 4
    max_parallel_maintenance_workers = 2
    max_parallel_workers = 8
    log_timezone = Asia/Shanghai
    timezone = Asia/Shanghai
  service:
    type: NodePort
    ports:
      postgresql: 5432
  persistence:
    size: 100Gi
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/postgresql="true"
    type: "soft"
    key: "kubernetes.service/postgresql"
    values:
      - "true"
