kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: stirling-pdf
  labels:
    app: stirling-pdf
spec:
  replicas: 1
  serviceName: stirling-pdf-headless
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      containers:
        - name: stirling-pdf
          image: 'registry.lingo.local/service/s-pdf:0.36.0-fat'
          ports:
            - name: http-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: DOCKER_ENABLE_SECURITY
              value: 'true'
            - name: SECURITY_ENABLE_LOGIN # 启用登录
              value: 'true'
            - name: SECURITY_INITIALLOGIN_USERNAME # 账号
              value: admin
            - name: SECURITY_INITIALLOGIN_PASSWORD # 密码
              value: Admin@123
            - name: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
              value: 'true'
            - name: LANGS
              value: zh_CN
          resources: {}
          volumeMounts:
            - name: stirling-pdf-data
              mountPath: /usr/share/tessdata
              subPath: trainingData
            - name: stirling-pdf-data
              mountPath: /configs
              subPath: extraConfigs
            - name: stirling-pdf-data
              mountPath: /logs
              subPath: logs
            - name: stirling-pdf-data
              mountPath: /customFiles
              subPath: customFiles
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.service/stirling-pdf
                    operator: In
                    values:
                      - "true"
              weight: 1
  volumeClaimTemplates:
    - metadata:
        name: stirling-pdf-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: openebs-hostpath
  serviceName: stirling-pdf-headless
---
kind: Service
apiVersion: v1
metadata:
  name: stirling-pdf-headless
  labels:
    app: stirling-pdf
spec:
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: stirling-pdf
  clusterIP: None
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: stirling-pdf
  labels:
    app: stirling-pdf
spec:
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: stirling-pdf
  type: NodePort
