---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      # CPU虚拟化20倍
      cpuAllocationRatio: 20
      # 内存虚拟化1.5倍
      memoryOvercommit: 150
      featureGates:
      - Root
      - HardDisk
      - DataVolumes
      - LiveMigration
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  imageRegistry: registry.lingo.local/kubevirt
  imageTag: v0.59.2
  workloadUpdateStrategy: {}

