fullnameOverride: "flink"
image:
  registry: registry.lingo.local
  repository: bitnami/flink
  tag: "1.19.1"
  pullPolicy: IfNotPresent
  debug: false
jobmanager:
  extraEnvVars:
    - name: TZ
      value: "Asia/Shanghai"
    # Default Value：$(grep -c ^processor /proc/cpuinfo)
    # resources.limits.cpu的值保持一致
    - name: FLINK_TASK_MANAGER_NUMBER_OF_TASK_SLOTS
      value: "2"
    # taskmanager.memory.process.size的值和resources.limits.memory保持一致
    - name: FLINK_PROPERTIES
      value: "jobmanager.memory.process.size: 4g\nparallelism.default: 1\njobmanager.execution.failover-strategy: region\nclassloader.resolve-order: parent-first"
  replicaCount: 1
  resourcesPreset: "none"
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  service:
    type: NodePort
    ports:
      rpc: 6123
      http: 8081
      blob: 6124
    nodePorts:
      rpc: ""
      http: ""
      blob: ""
  affinity: {}
  nodeSelector: {}
taskmanager:
  extraEnvVars:
    - name: TZ
      value: "Asia/Shanghai"
    # Default Value：$(grep -c ^processor /proc/cpuinfo)
    # resources.limits.cpu的值保持一致
    - name: FLINK_TASK_MANAGER_NUMBER_OF_TASK_SLOTS
      value: "8"
    # taskmanager.memory.process.size的值和resources.limits.memory保持一致
    - name: FLINK_PROPERTIES
      value: "taskmanager.memory.process.size: 8g\nparallelism.default: 1\njobmanager.execution.failover-strategy: region\nclassloader.resolve-order: parent-first"
  replicaCount: 2
  resourcesPreset: "none"
  resources:
    limits:
      cpu: "8"
      memory: "8Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  containerPorts:
    data: 6121
    rpc: 6122
  service:
    type: ClusterIP
    ports:
      data: 6121
      rpc: 6122
    nodePorts:
      data: ""
      rpc: ""
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/flink="true"
    type: "soft"
    key: "kubernetes.service/flink"
    values:
      - "true"
  # affinity: {}
  # nodeSelector: {}
  # terminationGracePeriodSeconds: "30"
