apiVersion: v1
kind: Service
metadata:
  name: vm-centos01
  namespace: kongyu-vm
  labels:
    kubevirt.io/vm: vm-centos01
spec:
  selector:
    kubevirt.io/vm: vm-centos01
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 38111
  type: NodePort
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-centos01
  name: vm-centos01
  namespace: kongyu-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-centos01
      annotations:
        "cni.projectcalico.org/ipAddrs": "[\"10.244.251.10\"]"
    spec:
      nodeSelector:
        kubernetes.io/hostname: server02.lingo.local
      domain:
        cpu:
          cores: 2
          model: host-passthrough
        memory:
          guest: 4Gi
        resources:
          overcommitGuestOverhead: true
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: emptydisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            bridge: {}
      terminationGracePeriodSeconds: 30
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: swr.cn-north-1.myhuaweicloud.com/kongyu/kubevirt/centos:centos7.9.2009
      - name: emptydisk
        emptyDisk:
          capacity: 20Gi
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #!/bin/sh
            echo Admin@123 | passwd --stdin root 
