kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-app
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      volumes:
        - name: app-storage
          emptyDir: {}
      initContainers:
        - name: download
          image: registry.lingo.local/service/busybox:1.36.1
          command:
            - sh
            - -c
            - |
              wget -O /opt/app/target/app.jar http://192.168.1.12:9000/test/spring/demo/integrated/springboot3-demo-v1.0.jar && \
              ls -l /opt/app/
          resources: {}
          volumeMounts:
            - name: app-storage
              mountPath: /opt/app/target
          imagePullPolicy: IfNotPresent
      containers:
        - name: app
          image: registry.lingo.local/service/java-app-separate:debian12_temurin_openjdk-jdk-21-jre
          env:
            - name: JAR_CMD
              value: "-jar /opt/app/app.jar"
            - name: JAVA_OPTS
              value: "-server -Xms128m -Xmx1024m"
            - name: SPRING_OPTS
              value: "--server.port=8080 --spring.profiles.active=prod"
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: app-storage
              mountPath: /opt/app/target
              readOnly: false
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: spring-app
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.service/spring-app
                    operator: In
                    values:
                      - "true"
              weight: 1
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  labels:
    app: spring-app
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30808

