fullnameOverride: "flink"
image:
  registry: registry.lingo.local
  repository: service/bitnami-flink
  tag: 1.19.1
  pullPolicy: IfNotPresent
  debug: false
jobmanager:
  extraEnvVars:
    - name: TZ
      value: "Asia/Shanghai"
    # Default Value：$(grep -c ^processor /proc/cpuinfo)
    - name: FLINK_TASK_MANAGER_NUMBER_OF_TASK_SLOTS
      value: "8"
    - name: FLINK_PROPERTIES
      value: "jobmanager.memory.process.size: 1g\nparallelism.default: 1\njobmanager.execution.failover-strategy: region\nclassloader.resolve-order: parent-first"
  replicaCount: 1
  resourcesPreset: "none"
  resources: {}
  containerPorts:
    rpc: 6123
    http: 8081
    blob: 6124
  service:
    type: NodePort
    ports:
      rpc: 6123
      http: 8081
      blob: 6124
    nodePorts:
      rpc: ""
      http: ""
      blob: ""
  affinity: {}
  nodeSelector: {}
taskmanager:
  extraEnvVars:
    - name: TZ
      value: "Asia/Shanghai"
    # Default Value：$(grep -c ^processor /proc/cpuinfo)
    - name: FLINK_TASK_MANAGER_NUMBER_OF_TASK_SLOTS
      value: "8"
    - name: FLINK_PROPERTIES
      value: "taskmanager.memory.process.size: 1g\nparallelism.default: 1\njobmanager.execution.failover-strategy: region\nclassloader.resolve-order: parent-first"
  replicaCount: 2
  resourcesPreset: "none"
  resources: {}
  containerPorts:
    data: 6121
    rpc: 6122
  service:
    type: ClusterIP
    ports:
      data: 6121
      rpc: 6122
    nodePorts:
      data: ""
      rpc: ""
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  # nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local ateng.kafka.controller=node
  #   type: "hard"
  #   key: "ateng.kafka.controller"
  #   values:
  #     - node
  # affinity: {}
  # nodeSelector: {}
  # terminationGracePeriodSeconds: "30"
