# 开发参考：https://kongyu666.github.io/dev/#/work/Ateng-Java/springboot3/doc/separate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-app-pvc
spec:
  #storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-app
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: spring-app-pvc
      initContainers:
        # 设置目录权限
        - name: change-permission
          image: registry.lingo.local/service/busybox:1.36.1
          command:
            - sh
            - -c
            - |
              if [ ! -d "/opt/app/lib" ]; then
                chown 1001:1001 -R /opt/app && \
                chmod 755 -R /opt/app
              fi
          volumeMounts:
            - name: app-storage
              mountPath: /opt/app
        # 下载源码Jar
        - name: download-source
          image: registry.lingo.local/service/busybox:1.36.1
          command:
            - sh
            - -c
            - |
              wget -O /opt/app/springboot2-demo-v1.0.jar http://192.168.1.12:9000/test/spring/demo/springboot3-demo-v1.0.jar && \
              ls -l /opt/app/springboot2-demo-v1.0.jar
          resources: {}
          volumeMounts:
            - name: app-storage
              mountPath: /opt/app
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
        # 下载源码Jar
        - name: download-dependency
          image: registry.lingo.local/service/busybox:1.36.1
          command:
            - sh
            - -c
            - |
              if [ ! -d "/opt/app/lib" ]; then
                wget -O /opt/app/lib.zip http://192.168.1.12:9000/test/spring/demo/lib.zip && \
                unzip -d /tmp /opt/app/lib.zip && \
                rm -f /opt/app/lib.zip && \
                chown 1001:1001 -R /tmp/lib && \
                mv /tmp/lib /opt/app/lib && \
                ls -l /opt/app/lib
              fi
          resources: {}
          volumeMounts:
            - name: app-storage
              mountPath: /opt/app
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
      containers:
        - name: app
          image: registry.lingo.local/service/java:debian12_temurin_openjdk-jdk-21-jre
          command:
            - java
          args:
            - -server
            - -Xms512m
            - -Xmx2048m
            - -jar
            - /opt/app/springboot2-demo-v1.0.jar
            - --spring.profiles.active=prod
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: app-storage
              mountPath: /opt/app
              readOnly: false
          #livenessProbe:
          #  httpGet:
          #    path: /actuator/health
          #    port: 8080
          #    scheme: HTTP
          #  initialDelaySeconds: 30
          #  timeoutSeconds: 1
          #  periodSeconds: 10
          #  successThreshold: 1
          #  failureThreshold: 3
          #readinessProbe:
          #  httpGet:
          #    path: /actuator/health
          #    port: 8080
          #    scheme: HTTP
          #  initialDelaySeconds: 10
          #  timeoutSeconds: 1
          #  periodSeconds: 10
          #  successThreshold: 1
          #  failureThreshold: 3
          #imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: spring-app
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.service/spring-app
                    operator: In
                    values:
                      - "true"
              weight: 1
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  labels:
    app: spring-app
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30808

