global:
  storageClass: "openebs-hostpath"
fullnameOverride: "mongodb"
image:
  registry: registry.lingo.local
  repository: service/mongodb-sharded
  tag: 7.0.4
  pullPolicy: IfNotPresent
  debug: false
auth:
  enabled: true
  rootUser: root
  rootPassword: "Admin@123"
shards: 3
common:
  mongodbEnableNumactl: false
  useHostnames: true
  mongodbEnableIPv6: false
  mongodbDirectoryPerDB: false
  mongodbSystemLogVerbosity: 0
  mongodbDisableSystemLog: false
  mongodbMaxWaitTimeout: 120
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  containerPorts:
    mongodb: 27017
service:
  name: ""
  type: NodePort
  ports:
    mongodb: 27017
  nodePorts:
    mongodb: ""
configsvr:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits: {}
    requests: {}
  affinity: {}
  nodeSelector: {}
mongos:
  replicas: 1
  resources:
    limits: {}
    requests: {}
  affinity: {}
  nodeSelector: {}
shardsvr:
  dataNode:
    replicas: 3
  resources:
    limits: {}
    requests: {}
    # resources:
    #   limits:
    #     cpu: "1"
    #     memory: "1Gi"
    #   requests:
    #     cpu: "500m"
    #     memory: "512Mi"
    # ## Allowed values: `soft` or `hard`
    # #podAffinityPreset: "soft"  ## 调度到同一节点
    # podAntiAffinityPreset: "hard"  ## 调度到不同节点
    # nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local ateng.kafka.controller=node
    #   type: "hard"
    #   key: "ateng.kafka.controller"
    #   values:
    #     - node
    # affinity: {}
    # nodeSelector: {}
    # terminationGracePeriodSeconds: "30"
  persistence:
    size: 10Gi
  arbiter:
    replicaCount: 0
