global:
  defaultStorageClass: ""
  security:
    allowInsecureImages: true
fullnameOverride: "cassandra"
image:
  registry: registry.lingo.local
  repository: bitnami/cassandra
  tag: "5.0.2"
  pullPolicy: IfNotPresent
  debug: false
dbUser:
  user: cassandra
  forcePassword: false
  password: "Admin@123"
cluster:
  name: cassandra
  seedCount: 1
  numTokens: 256
  datacenter: dc1
  rack: rack1
  endpointSnitch: SimpleSnitch
  clientEncryption: false
jvm:
  extraOpts: ""
  maxHeapSize: ""
  newHeapSize: ""
extraEnvVars:
  - name: TZ
    value: "Asia/Shanghai"
replicaCount: 1
resourcesPreset: "none"
#resources: {}
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 2
    memory: 2048Mi
affinity: {}
nodeSelector: {}
podAntiAffinityPreset: "soft"  ## 调度到不同节点
nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/cassandra="true"
  type: "soft"
  key: "kubernetes.service/cassandra"
  values:
    - "true"
terminationGracePeriodSeconds: "60"
service:
  type: NodePort
  ports:
    cql: 9042
    metrics: 8080
  nodePorts:
    cql: ""
    metrics: ""
persistence:
  enabled: true
  size: 100Gi
  commitLogsize: 10Gi
