global:
  storageClass: "openebs-hostpath"
fullnameOverride: "flink"
image:
  registry: registry.lingo.local
  repository: service/bitnami-flink
  tag: 1.18.0
  pullPolicy: IfNotPresent
  debug: false
jobmanager:
  extraEnvVars:
    - name: TZ
      value: "Asia/Shanghai"
  replicaCount: 1
  containerPorts:
    rpc: 6123
    http: 8081
    blob: 6124
  service:
    type: NodePort
    ports:
      rpc: 6123
      http: 8081
      blob: 6124
    nodePorts:
      rpc: ""
      http: ""
      blob: ""
  affinity: {}
  nodeSelector: {}
taskmanager:
  extraEnvVars:
    - name: TZ
      value: "Asia/Shanghai"
  replicaCount: 2
  containerPorts:
    data: 6121
    rpc: 6122
  service:
    type: ClusterIP
    ports:
      data: 6121
      rpc: 6122
    nodePorts:
      data: ""
      rpc: ""
  resources:
    limits: {}
    requests: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  # podAntiAffinityPreset: "hard"  ## 调度到不同节点
  # nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local ateng.kafka.controller=node
  #   type: "hard"
  #   key: "ateng.kafka.controller"
  #   values:
  #     - node
  # affinity: {}
  # nodeSelector: {}
  # terminationGracePeriodSeconds: "30"
