global:
  defaultStorageClass: ""
  kibanaEnabled: true
fullnameOverride: "elasticsearch"
clusterName: elastic
#plugins: "https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-phonetic/analysis-phonetic-7.17.26.zip https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-icu/analysis-icu-7.17.26.zip https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-smartcn/analysis-smartcn-7.17.26.zip"
#plugins: "http://miniserve.lingo.local/elasticsearch-plugins/v7.17.26/analysis-icu-7.17.26.zip http://miniserve.lingo.local/elasticsearch-plugins/v7.17.26/analysis-phonetic-7.17.26.zip http://miniserve.lingo.local/elasticsearch-plugins/v7.17.26/analysis-smartcn-7.17.26.zip"
plugins: ""
snapshotRepoPath: "/bitnami/elasticsearch/data/snap"
extraConfig:
  xpack:
    security:
      enabled: false
  http:
    cors:
      enabled: true
      allow-origin: "*"
extraEnvVars:
  - name: TZ
    value: Asia/Shanghai
image:
  registry: registry.lingo.local
  repository: bitnami/elasticsearch
  tag: "7.17.26"
  pullPolicy: IfNotPresent
  debug: false
security:
  enabled: true
  elasticPassword: "Admin@123"
  fipsMode: false
  tls:
    restEncryption: false
    autoGenerated: true
    verificationMode: "full"
    usePemCerts: true
service:
  type: NodePort
  ports:
    restAPI: 9200
    transport: 9300
  nodePorts:
    restAPI: ""
    transport: ""
master:
  masterOnly: true
  replicaCount: 1
  extraRoles: []
  persistence:
    enabled: true
    size: 10Gi
  heapSize: 1024m
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/elasticsearch="true"
    type: "soft"
    key: "kubernetes.service/elasticsearch"
    values:
      - "true"
data:
  replicaCount: 2
  extraRoles: []
  persistence:
    enabled: true
    size: 100Gi
  heapSize: 2048m
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/elasticsearch="true"
    type: "soft"
    key: "kubernetes.service/elasticsearch"
    values:
      - "true"
coordinating:
  replicaCount: 1
  extraRoles: []
  heapSize: 1024m
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/elasticsearch="true"
    type: "soft"
    key: "kubernetes.service/elasticsearch"
    values:
      - "true"
ingest:
  enabled: false
  replicaCount: 2
  extraRoles: []
  containerPorts:
    restAPI: 9200
    transport: 9300
  heapSize: 1024m
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/elasticsearch="true"
    type: "soft"
    key: "kubernetes.service/elasticsearch"
    values:
      - "true"
  service:
    enabled: false
    type: ClusterIP
    ports:
      restAPI: 9200
      transport: 9300
    nodePorts:
      restAPI: ""
      transport: ""
metrics:
  enabled: false
  image:
    registry: registry.lingo.local
    repository: bitnami/elasticsearch-exporter
    tag: "1.8.0"
    pullPolicy: IfNotPresent
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-weight: "5"
  service:
    type: ClusterIP
    port: 9114
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9114"
  resourcesPreset: "none"
  resources: {}
  serviceMonitor:
    enabled: false
    namespace: ""
    jobLabel: ""
    interval: ""
    scrapeTimeout: ""
    relabelings: []
    metricRelabelings: []
    selector: {}
    labels: {}
    honorLabels: false
  prometheusRule:
    enabled: false
    namespace: ""
    additionalLabels: {}
    rules: []

kibana:
  image:
    registry: registry.lingo.local
    repository: bitnami/kibana
    tag: "7.17.26"
    pullPolicy: IfNotPresent
    debug: false
  service:
    type: NodePort
    ports:
      http: 5601
    nodePorts:
      http: ""
  resourcesPreset: "none"
  resources: {}
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  persistence:
    enabled: true
    size: 10Gi
  elasticsearch:
    hosts:
      - '{{ include "elasticsearch.service.name" . }}'
    port: '{{ include "elasticsearch.service.ports.restAPI" . }}'
    security:
      auth:
        enabled: true
        kibanaPassword: "Admin@123"
        createSystemUser: true
        elasticsearchPasswordSecret: "elasticsearch"
