apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-retry-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy-retry-server
  template:
    metadata:
      labels:
        app: easy-retry-server
    spec:
      containers:
      - name: easy-retry-server
        image: registry.lingo.local/service/easy-retry:2.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: netty
          containerPort: 1788
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        - name: PARAMS
          value: "--easy-retry.db-type=mysql  --spring.datasource.username=root --spring.datasource.password=Admin@123  --spring.datasource.url=jdbc:mysql://192.168.1.10:35725/ateng_easy_retry?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: easy-retry-server
  labels:
    app: easy-retry-server
spec:
  selector:
    app: easy-retry-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32781
    - name: netty
      protocol: TCP
      port: 1788
      targetPort: 1788
      nodePort: 32782
  type: NodePort
