apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: ceph-user
  namespace: rook-ceph
spec:
  store: ceph-objectstore
  displayName: "ceph user"
  # Quotas set on the user
  # quotas:
     # maxBuckets: 100
     # maxSize: 10G
     # maxObjects: 10000
  # Additional permissions given to the user
  # capabilities:
     # user: "*"
     # bucket: "*"
     # metadata: "*"
     # usage: "*"
     # zone: "*"

