apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-test
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-server
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-test
  namespace: default
  labels:
    app.kubernetes.io/name: busybox-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: busybox-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: busybox-test
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: busybox
          image: registry.lingo.local/kubernetes/busybox:1.35.0
          imagePullPolicy: "IfNotPresent"
          command:
            - /bin/sh
          args:
            - -c
            - 'while true; do echo $(hostname):$(date "+%Y-%m-%d %H:%M:%S") >> /data/date.txt; tail -3 /data/date.txt;sleep 10; done'
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: busybox-test
---

