global:
  defaultStorageClass: ""
  security:
    allowInsecureImages: true
fullnameOverride: "gitea"
image:
  registry: registry.lingo.local
  repository: bitnami/gitea
  tag: "1.23.7"
  pullPolicy: IfNotPresent
  debug: false
adminUsername: root
adminPassword: "Admin@123"
adminEmail: 2385569970@qq.com
appName: gitea
runMode: prod
exposeSSH: true
extraEnvVars:
  - name: TZ
    value: "Asia/Shanghai"
  - name: GITEA_DOMAIN
    value: "192.168.1.10"
smtpHost: ""
smtpPort: ""
smtpUser: ""
smtpPassword: ""
containerPorts:
  http: 3000
  ssh: 2222
persistence:
  enabled: true
  size: 100Gi
service:
  type: NodePort
  ports:
    http: 80
    ssh: 32222
  nodePorts:
    http: "33000"
    ssh: "32222"
resourcesPreset: "none"
resources: {}
affinity: {}
nodeSelector: {}
# resources:
#   limits:
#     cpu: "1"
#     memory: "1Gi"
#   requests:
#     cpu: "500m"
#     memory: "512Mi"
# ## Allowed values: `soft` or `hard`
# #podAffinityPreset: "soft"  ## 调度到同一节点
podAntiAffinityPreset: "soft"  ## 调度到不同节点
nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/gitea="true"
  type: "soft"
  key: "kubernetes.service/gitea"
  values:
    - "true"
postgresql:
  enabled: true
  auth:
    postgresPassword: "Admin@123"
    username: bn_gitea
    password: ""
    database: bitnami_gitea
  architecture: standalone
  primary:
    name: primary
    extendedConfiguration: |-
      max_connections = 1024
      shared_buffers = 1GB
      work_mem = 32MB
      max_parallel_workers_per_gather = 2
      max_parallel_maintenance_workers = 1
      max_parallel_workers = 2
      log_timezone = Asia/Shanghai
      timezone = Asia/Shanghai
    service:
      type: ClusterIP
      ports:
        postgresql: 5432
    persistence:
      size: 100Gi
    extraEnvVars:
      - name: TZ
        value: Asia/Shanghai
    resourcesPreset: "none"
    resources: {}
    affinity: {}
    nodeSelector: {}
    # resources:
    #   limits:
    #     cpu: "1"
    #     memory: "1Gi"
    #   requests:
    #     cpu: "500m"
    #     memory: "512Mi"
    # ## Allowed values: `soft` or `hard`
    # #podAffinityPreset: "soft"  ## 调度到同一节点
    podAntiAffinityPreset: "soft"  ## 调度到不同节点
    nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/gitea="true"
      type: "soft"
      key: "kubernetes.service/gitea"
      values:
        - "true"
externalDatabase: {}
