global:
  defaultStorageClass: ""
fullnameOverride: "redis"
image:
  debug: false
  registry: registry.lingo.local
  repository: service/redis-cluster
  tag: 7.4.1
  pullPolicy: IfNotPresent
usePassword: true
password: "Admin@123"
service:
  ports:
    redis: 6379
  nodePorts:
    redis: ""
  type: ClusterIP
persistence:
  size: 50Gi
redis:
  useAOFPersistence: "yes"
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
    - name: REDIS_IO_THREADS
      value: "10"
    - name: REDIS_IO_THREADS_DO_READS
      value: "yes"
    - name: REDIS_MAXCLIENTS
      value: "10000"
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/redis="true"
    type: "soft"
    key: "kubernetes.service/redis"
    values:
      - "true"
cluster:
  init: true
  nodes: 6
  replicas: 1
