global:
  defaultStorageClass: ""
  security:
    allowInsecureImages: true
fullnameOverride: "jaeger"
image:
  registry: registry.lingo.local
  repository: bitnami/jaeger
  tag: "2.4.0"
  pullPolicy: IfNotPresent
  debug: false
query:
  extraEnvVars:
    - name: TZ
      value: "Asia/Shanghai"
  replicaCount: 1
  service:
    type: NodePort
    ports:
      api: 16686
      admin: 16687
    nodePorts:
      api: ""
      admin: ""
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/jaeger="true"
    type: "soft"
    key: "kubernetes.service/jaeger"
    values:
      - "true"
collector:
  extraEnvVars:
    - name: TZ
      value: "Asia/Shanghai"
  replicaCount: 1
  service:
    type: ClusterIP
    ports:
      jaeger: 9411
      grpc: 14250
      binary: 14268
      admin: 14269
      otlp:
        grpc: 4317
        http: 4318
    nodePorts:
      jaeger: ""
      grpc: ""
      binary: ""
      admin: ""
      otlp:
        grpc: ""
        http: ""
  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/jaeger="true"
    type: "soft"
    key: "kubernetes.service/jaeger"
    values:
      - "true"
migration:
  extraEnvVars:
    - name: TZ
      value: "Asia/Shanghai"
  resourcesPreset: "none"
  resources: {}
  initContainer:
    resourcesPreset: "none"
    resources: {}
cqlshImage:
  registry: registry.lingo.local
  repository: bitnami/cassandra
  tag: "5.0.3"
  pullPolicy: IfNotPresent
  resourcesPreset: "none"
  resources: {}
  debug: false
cassandra:
  enabled: true
  image:
    registry: registry.lingo.local
    repository: bitnami/cassandra
    tag: "5.0.3"
    pullPolicy: IfNotPresent
    debug: false
  cluster:
    name: cassandra
    seedCount: 1
    numTokens: 256
    datacenter: dc1
    rack: rack1
    endpointSnitch: SimpleSnitch
    clientEncryption: false
  keyspace: "ateng_jaeger"
  dbUser:
    user: cassandra
    password: "Admin@123"
  service:
    ports:
      cql: 9042
  replicaCount: 1
  resourcesPreset: "none"
  resources: {}
  extraEnvVars:
    - name: CASSANDRA_CFG_YAML_SASI_INDEXES_ENABLED
      value: "true"
    - name: TZ
      value: "Asia/Shanghai"
  persistence:
    enabled: true
    size: 100Gi
    commitLogsize: 10Gi
