global:
  defaultStorageClass: ""
  security:
    allowInsecureImages: true
fullnameOverride: "memcached"
image:
  registry: registry.lingo.local
  repository: bitnami/memcached
  tag: "1.6.38"
  pullPolicy: IfNotPresent
## @param architecture Memcached architecture. Allowed values: standalone or high-availability
architecture: high-availability
auth:
  enabled: false
  username: ""
  password: ""
replicaCount: 3
resourcesPreset: "none"
resources: {}
affinity: {}
nodeSelector: {}
# resources:
#   limits:
#     cpu: "1"
#     memory: "1Gi"
#   requests:
#     cpu: "500m"
#     memory: "512Mi"
# ## Allowed values: `soft` or `hard`
# #podAffinityPreset: "soft"  ## 调度到同一节点
podAntiAffinityPreset: "soft"  ## 调度到不同节点
nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/memcached="true"
  type: "soft"
  key: "kubernetes.service/memcached"
  values:
    - "true"
extraEnvVars:
  - name: TZ
    value: Asia/Shanghai
service:
  type: NodePort
  ports:
    memcached: 11211
  nodePorts:
    memcached: ""
persistence:
  enabled: true
  size: 10Gi
