apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot3-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot3-admin
  template:
    metadata:
      labels:
        app: springboot3-admin
    spec:
      containers:
        - name: springboot3-admin
          image: 'registry.lingo.local/service/springboot-admin:3.3.0'
          ports:
            - name: http-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPTS
              value: '-server -Xms128m -Xmx1g -Dfile.encoding=UTF-8'
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - 'curl -X POST http://localhost:8080/actuator/shutdown'
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: springboot3-admin
  labels:
    app: springboot3-admin
spec:
  selector:
    app: springboot3-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
