---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pi-tmp
  namespace: ateng-spark
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: ateng-spark
spec:
  type: Scala
  mode: cluster
  image: "registry.lingo.local/service/spark:3.5.4"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  arguments:
    - "10000"
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.5.4.jar"
  #mainApplicationFile: "http://192.168.1.12:9000/data/bigdata/flink/jars/spark-examples_2.12-3.5.4.jar"
  sparkVersion: "3.5.4"
  sparkUIOptions:
    serviceType: NodePort
  dynamicAllocation:
    enabled: true
    initialExecutors: 2
    maxExecutors: 5
    minExecutors: 1
  restartPolicy:
    type: Never
  volumes:
    - name: "tmp-volume"
      persistentVolumeClaim:
        claimName: spark-pi-tmp
  driver:
    cores: 2
    coreLimit: "2"
    coreRequest: "1"
    memory: "2g"
    env:
      - name: TZ
        value: Asia/Shanghai
    labels:
      version: 3.5.4
      app.kubernetes.io/name: spark-pi
      app.kubernetes.io/component: driver
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: "tmp-volume"
        mountPath: "/tmp"
  executor:
    cores: 2
    coreLimit: "2"
    coreRequest: "1"
    memory: "4g"
    instances: 1
    env:
      - name: TZ
        value: Asia/Shanghai
      - name: "MY_ENV_VAR"
        value: "some_value"
      - name: "ANOTHER_VAR"
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: my-key
    labels:
      version: 3.5.4
      app.kubernetes.io/name: spark-pi
      app.kubernetes.io/component: executor
    volumeMounts:
      - name: "tmp-volume"
        mountPath: "/tmp"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: spark-pi
                  app.kubernetes.io/component: executor
              topologyKey: kubernetes.io/hostname
            weight: 1
