apiVersion: kubevirt.io/v1
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: vmr-centos7.9
  labels:
    kubevirt.io/vm: vmr-centos7.9
spec:
  replicas: 3
  selector:
    matchLabels:
      kubevirt.io/vm: vmr-centos7.9
  template:
    metadata:
      name: vmr-centos7.9
      labels:
        kubevirt.io/vm: vmr-centos7.9
    spec:
      hostname: "centos"
      domain:
        ## This is not related to scheduling decisions or resource assignment
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        resources:
          requests:
            memory: 1Gi
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: emptydisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            bridge: {}
      terminationGracePeriodSeconds: 0
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: swr.cn-north-1.myhuaweicloud.com/kongyu/kubevirt/centos:centos7.9.2009
      - name: emptydisk
        emptyDisk:
          capacity: 10Gi
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #!/bin/sh
            echo Admin@123 | passwd --stdin root

