apiVersion: v1
kind: Service
metadata:
  name: vmr-openeuler
  labels:
    kubevirt.io/vm: vmr-openeuler
spec:
  selector:
    kubevirt.io/vm: vmr-openeuler
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
  type: NodePort
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: vmr-openeuler
  labels:
    kubevirt.io/vm: vmr-openeuler
spec:
  replicas: 3
  selector:
    matchLabels:
      kubevirt.io/vm: vmr-openeuler
  template:
    metadata:
      name: vmr-openeuler
      labels:
        kubevirt.io/vm: vmr-openeuler
    spec:
      hostname: "openeuler"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    kubevirt.io/vm: vmr-openeuler
                topologyKey: kubernetes.io/hostname
              weight: 1
      domain:
        cpu:
          cores: 8
          model: host-passthrough
        memory:
          guest: 16Gi
        resources:
          overcommitGuestOverhead: true
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: emptydisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            bridge: {}
      terminationGracePeriodSeconds: 30
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: swr.cn-north-1.myhuaweicloud.com/kongyu/kubevirt/linux:openeuler-24.03-lts-x86_64
      - name: emptydisk
        emptyDisk:
          capacity: 100Gi
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #!/bin/sh
            echo Admin@123 | passwd --stdin root 
            sed -i "s#PasswordAuthentication.*#PasswordAuthentication yes#g" /etc/ssh/sshd_config.d/50-cloud-init.conf
            systemctl restart sshd
