## velero镜像
image:
  repository: registry.lingo.local/kubernetes/velero
  tag: v1.9.0
  pullPolicy: IfNotPresent

## 供应商的插件(MinIO兼容AWS)
initContainers:
   - name: velero-plugin-for-aws
     image: registry.lingo.local/kubernetes/velero-plugin-for-aws:v1.5.0
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - mountPath: /target
         name: plugins

## 指定Velero部署的资源请求/限制
resources:
  limits: {}
  requests: {}
  #requests:
  #  cpu: 500m
  #  memory: 128Mi
  #limits:
  #  cpu: 1000m
  #  memory: 512Mi

kubectl:
  image:
    repository: registry.lingo.local/kubernetes/kubectl
    tag: 1.23.12

## 升级或者删除时更新CRD
upgradeCRDs: true
cleanUpCRDs: true

configuration:
  ## 供应商(MinIO兼容AWS)
  ## https://velero.io/docs/v1.6/supported-providers/
  provider: aws

  # Parameters for the `default` BackupStorageLocation. See
  # https://velero.io/docs/v1.6/api-types/backupstoragelocation/
  backupStorageLocation:
    ## 备份存储位置名称(BackupStorageLocation)
    name: minio
    ## 备份存储位置供应商
    provider: aws
    ## 供应商存储桶名
    bucket: k8s-velero
    ## 存储路径路径名称
    prefix: velero
    ## 备份存储位置是否为默认(BackupStorageLocation)
    default: true
    ## 备份存储位置权限
    accessMode: ReadWrite
    ## 供应商的region和s3Url
    config:
      region: minio
      s3ForcePathStyle: true
      s3Url: http://192.168.1.101:9000

  # Parameters for the `default` VolumeSnapshotLocation. See
  # https://velero.io/docs/v1.6/api-types/volumesnapshotlocation/
  volumeSnapshotLocation:
    ## 快照的卷快照位置名称(VolumeSnapshotLocation)
    name: minio
    ## 备份存储位置供应商
    provider: aws
    ## ## 供应商的region和s3Url
    config:
      region: minio

  # additional key/value pairs to be used as environment variables such as "AWS_CLUSTER_NAME: 'yourcluster.domain.tld'"
  extraEnvVars: {"TZ":"Asia/Shanghai"}

credentials:
  ## 供应商的AK SK
  useSecret: true
  name: minio
  ## [AWS] https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/README.md
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=admin
      aws_secret_access_key=Admin@123

## 启动BackupStorageLocation
backupsEnabled: true
## 启动VolumeSnapshotLocation
snapshotsEnabled: true

## 部署restic
deployRestic: true
## 指定restic部署的资源请求/限制
restic:
  podVolumePath: /var/lib/kubelet/pods
  privileged: false
  # Pod priority class name to use for the Restic daemonset. Optional.
  priorityClassName: ""
  # Resource requests/limits to specify for the Restic daemonset deployment. Optional.
  # https://velero.io/docs/v1.6/customize-installation/#customize-resource-requests-and-limits
  resources:
    limits: {}
    requests: {}
    #requests:
    #  cpu: 500m
    #  memory: 512Mi
    #limits:
    #  cpu: 1000m
    #  memory: 1024Mi

# Velero ConfigMaps.
configMaps:
  restic-restore-action-config:
    labels:
      velero.io/plugin-config: ""
      velero.io/restic: RestoreItemAction
    data:
      image: registry.lingo.local/kubernetes/velero-restic-restore-helper:v1.9.0
