apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:  
    matchLabels:
      app: nginx
  template:  
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-shared-ip
  annotations:
    metallb.universe.tf/allow-shared-ip: "service-192.168.1.250"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.1.250
  ports:
    - name: http
      port: 80
      targetPort: 80

