apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: win10
  labels:
    app: win10
spec:
  serviceName: "win10"
  replicas: 1
  selector:
    matchLabels:
      app: win10
  template:
    metadata:
      labels:
        app: win10
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.service/win10
                    operator: In
                    values:
                      - "true"
              weight: 1
      terminationGracePeriodSeconds: 120
      containers:
      - name: win10
        image: registry.lingo.local/service/windows:4.06
        ports:
        - containerPort: 8006
          protocol: TCP
        - containerPort: 3389
          protocol: TCP
        - containerPort: 3389
          protocol: UDP
        env:
        - name: VERSION
          value: "http://192.168.1.12:9000/public-bucket/images/zh-cn_windows_10_business_editions_version_22h2_updated_sep_2024_x64_dvd_1be03898.iso"
        - name: LANGUAGE
          value: "Chinese"
        - name: REGION
          value: "zh_CN"
        - name: KEYBOARD
          value: "zh_CN"
        - name: USERNAME
          value: "admin"
        - name: PASSWORD
          value: "Admin@123"
        - name: RAM_SIZE
          value: "4G"
        - name: CPU_CORES
          value: "2"
        - name: DISK_SIZE
          value: "100G"
        volumeMounts:
        - mountPath: /storage
          name: storage
        - mountPath: /dev/kvm
          name: dev-kvm
        securityContext:
          privileged: true
      volumes:
        - name: dev-kvm
          hostPath:
            path: /dev/kvm
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: openebs-hostpath
      resources:
        requests:
          storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: win10
  labels:
    app: win10
spec:
  selector:
    app: win10
  ports:
    - name: tcp-8006
      protocol: TCP
      port: 8006
      targetPort: 8006
    - name: tcp-3389
      protocol: TCP
      port: 3389
      targetPort: 3389
    - name: udp-3389
      protocol: UDP
      port: 3389
      targetPort: 3389
  type: NodePort
