apiVersion: v1
kind: Pod
metadata:
  name: pod-interface
  annotations:
    k8s.v1.cni.cncf.io/networks: kube-system/macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
# kubectl exec -it pod-interface -- ip a
