kind: Deployment
apiVersion: apps/v1
metadata:
  name: kkfileview
  labels:
    app: kkfileview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kkfileview
  template:
    metadata:
      labels:
        app: kkfileview
    spec:
      volumes:
        - name: app-storage
          emptyDir: {}
      containers:
        - name: app
          image: registry.lingo.local/service/kkfileview:v4.4.0
          ports:
            - name: web
              containerPort: 8012
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: app-storage
              mountPath: /opt/kkFileView-4.4.0/file
              readOnly: false
          livenessProbe:
            httpGet:
              path: /listFiles
              port: 8012
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /listFiles
              port: 8012
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: kkfileview
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.service/kkfileview
                    operator: In
                    values:
                      - "true"
              weight: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kkfileview-service
  labels:
    app: kkfileview
spec:
  type: NodePort
  selector:
    app: kkfileview
  ports:
  - name: web
    protocol: TCP
    port: 8012
    targetPort: 8012
