apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-view-config
data:
  config.yml: |
    log:
      storageDays: 4          # 日志保留天数
      logDir: "logs"          # 日志保留文件夹
    port: 8090                # 启动端口
    pluginRpcPort: 8091       # 插件内网访问端口
    rootUrl: http://192.168.1.10:38090/  # 项目访问根目录
    dbType: "sqlite3"         # 数据保留类型 分为 sqlite3 和 mysql
    enableLogEs: false        # 是否记录 es 请求记录
    enableLogEsRes: false     # 是否记录 es 请求记录中返回的响应体
    sqlite:                   # dbType 为 sqlite3 时填 dbPath 为数据保存文件地址
      dbName: "es_view.db"
    mysql:                    # dbType 为 mysql 时填
      username: "root"
      pwd: ""
      ip: "localhost"
      port: "3306"
      dbName: "test"
      maxOpenConns: 10
      maxIdleConns: 10
    esPwdSecret: "concat_mail!!->1340691923@qq.com" # es 密码加密密钥
    version: "0.0.7"          # EV 版本号
    deBug: false              # 是否为测试模式
    checkForevUpdates: true   # 是否自动检测 ev 更新
    checkForPluginUpdates: true  # 是否自动检测 ev 插件更新
    evKey:                    # evKey 需要到插件者后台注册获取
    storeFileDir: store_file_dir # 临时文件存放目录
    plugin:
      loadPath: plugins       # 插件存放目录
      storePath: plugins_store # 插件临时文件存放目录
    watermarkContent: ElasticView # 水印
    translation:
      lang: zh-cn             # zh-cn 或 en
      cfgDir: config/ev-i18n  # i18n 文件存放目录
    oauth:
      workwechat:
        agentid: ""
        corpid: ""
        enable: false
        secert: ""
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-view
  labels:
    app: elastic-view
spec:
  serviceName: "elastic-view"
  replicas: 1
  selector:
    matchLabels:
      app: elastic-view
  template:
    metadata:
      labels:
        app: elastic-view
    spec:
      containers:
      - name: elastic-view
        image: registry.lingo.local/service/elastic_view:v0.0.7
        ports:
        - name: tcp-8090
          containerPort: 8090
          protocol: TCP
        env:
          - name: TZ
            value: Asia/Shanghai
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        - name: config-volume
          mountPath: /app/config/config.yml
          subPath: config.yml
        - name: data-volume
          mountPath: /app/data
        - name: plugins-volume
          mountPath: /app/plugins
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
          type: ''
      - name: config-volume
        configMap:
          name: elastic-view-config
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "openebs-hostpath"
        resources:
          requests:
            storage: 10Gi  # 根据需求调整存储大小
    - metadata:
        name: plugins-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "openebs-hostpath"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-view
  labels:
    app: elastic-view
spec:
  ports:
    - name: http-8090
      protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 38090
  selector:
    app: elastic-view
  type: NodePort
