apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: win11-tiny-2311
spec:
  serviceName: "win11-tiny-2311"
  replicas: 1
  selector:
    matchLabels:
      app: win11-tiny-2311
  template:
    metadata:
      labels:
        app: win11-tiny-2311
    spec:
      nodeSelector:
        kubernetes.io/hostname: "server02.lingo.local"
      terminationGracePeriodSeconds: 120 # the Kubernetes default is 30 seconds and it may be not enough
      containers:
      - name: win11-tiny-2311
        image: dockurr/windows
        ports:
        - containerPort: 8006
          protocol: TCP
        - containerPort: 3389
          protocol: TCP
        - containerPort: 3389
          protocol: UDP
        env:
        - name: VERSION
          value: "http://192.168.1.12:9000/public-bucket/images/tiny11_2311_x64.iso"
        - name: USERNAME
          value: "admin"
        - name: PASSWORD
          value: "Admin@123"
        - name: RAM_SIZE
          value: "4G"
        - name: CPU_CORES
          value: "2"
        - name: DISK_SIZE
          value: "100G"
        volumeMounts:
        - mountPath: /storage
          name: storage
        - mountPath: /dev/kvm
          name: dev-kvm
        securityContext:
          privileged: true
      volumes:
        - name: dev-kvm
          hostPath:
            path: /dev/kvm
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: openebs-hostpath
      resources:
        requests:
          storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: win11-tiny-2311
spec:
  selector:
    app: win11-tiny-2311
  ports:
    - name: tcp-8006
      protocol: TCP
      port: 8006
      targetPort: 8006
    - name: tcp-3389
      protocol: TCP
      port: 3389
      targetPort: 3389
    - name: udp-3389
      protocol: UDP
      port: 3389
      targetPort: 3389
  type: NodePort

